# Generated by Django 3.2.5 on 2021-07-28 20:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Advertisement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('advertisement_id', models.IntegerField(db_index=True, unique=True, verbose_name='Id объявления')),
                ('advertisement_url', models.CharField(max_length=300, verbose_name='Ссылка на объявление')),
                ('brand', models.CharField(max_length=50, verbose_name='Марка')),
                ('model', models.CharField(max_length=200, verbose_name='Модель')),
                ('year', models.CharField(max_length=4, verbose_name='Год авто')),
                ('color', models.CharField(blank=True, max_length=15, verbose_name='Цвет автомобиля')),
                ('info', models.TextField(verbose_name='Текст объявление')),
                ('site', models.CharField(max_length=30, verbose_name='Сайт объявления')),
                ('latitude', models.CharField(blank=True, max_length=20, verbose_name='Широта')),
                ('longitude', models.CharField(blank=True, max_length=20, verbose_name='Долгота')),
                ('run', models.IntegerField(blank=True, null=True, verbose_name='Пробег')),
                ('price', models.IntegerField(blank=True, null=True, verbose_name='Цена')),
                ('original', models.BooleanField(null=True, verbose_name='Оригинальное объявление')),
                ('created_at', models.DateTimeField(db_index=True, verbose_name='Дата добавления в базу')),
                ('added_at', models.DateTimeField(blank=True, verbose_name='Дата появления объявления')),
            ],
        ),
        migrations.CreateModel(
            name='AdvertisementPhotos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo_url', models.CharField(max_length=200, verbose_name='Ссылка на изображение')),
                ('photo', models.ImageField(null=True, upload_to='', verbose_name='Изображение')),
                ('avg_hash', models.CharField(max_length=16, null=True, verbose_name='Изображение')),
                ('adv_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='search_cars.advertisement', verbose_name='Объявление')),
            ],
        ),
        migrations.AddField(
            model_name='advertisement',
            name='photos',
            field=models.ManyToManyField(to='search_cars.AdvertisementPhotos', verbose_name='Ссылки на фотографии'),
        ),
        migrations.AddField(
            model_name='advertisement',
            name='similar_advertisement',
            field=models.ManyToManyField(blank=True, related_name='_search_cars_advertisement_similar_advertisement_+', to='search_cars.Advertisement'),
        ),
    ]
