# Generated by Django 3.2.3 on 2021-07-04 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Advertisement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.CharField(max_length=300, verbose_name='ссылка на обьявление')),
                ('inner_adv_id', models.IntegerField(verbose_name='внутренний id')),
                ('brand', models.CharField(max_length=50, verbose_name='Марка')),
                ('model', models.CharField(max_length=200, verbose_name='модель')),
                ('year', models.CharField(max_length=4, verbose_name='год авто')),
                ('text', models.TextField(verbose_name='текст обьявление')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата добавления')),
                ('added_at', models.DateTimeField(blank=True, verbose_name='Дата добавления во внешнюю систему')),
                ('original', models.BooleanField(default=True, verbose_name='Оригинальность')),
                ('duplicates', models.ManyToManyField(blank=True, related_name='_search_cars_advertisement_duplicates_+', to='search_cars.Advertisement')),
            ],
        ),
    ]
