# Generated by Django 3.2.3 on 2021-07-06 14:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('search_cars', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='advertisement',
            old_name='inner_adv_id',
            new_name='advertisement_id',
        ),
        migrations.RenameField(
            model_name='advertisement',
            old_name='link',
            new_name='advertisement_url',
        ),
        migrations.RenameField(
            model_name='advertisement',
            old_name='text',
            new_name='info',
        ),
        migrations.RemoveField(
            model_name='advertisement',
            name='duplicates',
        ),
        migrations.CreateModel(
            name='AdvertisementPhotos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo_url', models.CharField(max_length=200, verbose_name='ссылка на обьявление')),
                ('avg_hash', models.CharField(default='', max_length=20, verbose_name='хэш картинки')),
                ('d_hash', models.CharField(default='', max_length=20, verbose_name='d-хэш картинки')),
                ('p_hash', models.CharField(default='', max_length=20, verbose_name='p-хэш картинки')),
                ('w_hash', models.CharField(default='', max_length=20, verbose_name='w-хэш картинки')),
                ('adv_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='search_cars.advertisement')),
            ],
        ),
    ]
