# Generated by Django 3.2.3 on 2021-07-06 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search_cars', '0002_auto_20210706_1700'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='advertisement',
            name='original',
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='advertisement_id',
            field=models.IntegerField(unique=True, verbose_name='внутренний id'),
        ),
    ]
