# Generated by Django 3.2.3 on 2021-07-07 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search_cars', '0003_auto_20210706_2052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisement',
            name='added_at',
            field=models.DateTimeField(blank=True, verbose_name='Дата появления объявления'),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='created_at',
            field=models.DateTimeField(db_index=True, verbose_name='Дата добавления в базу данных'),
        ),
    ]
