# Generated by Django 3.2.3 on 2021-07-07 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search_cars', '0004_auto_20210707_1400'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='advertisementphotos',
            name='adv_id',
        ),
        migrations.AddField(
            model_name='advertisement',
            name='photos',
            field=models.ManyToManyField(to='search_cars.AdvertisementPhotos', verbose_name='Ссылки на фотографии'),
        ),
        migrations.AlterField(
            model_name='advertisementphotos',
            name='avg_hash',
            field=models.CharField(max_length=20, verbose_name='хэш картинки'),
        ),
        migrations.AlterField(
            model_name='advertisementphotos',
            name='d_hash',
            field=models.CharField(max_length=20, verbose_name='d-хэш картинки'),
        ),
        migrations.AlterField(
            model_name='advertisementphotos',
            name='p_hash',
            field=models.CharField(max_length=20, verbose_name='p-хэш картинки'),
        ),
        migrations.AlterField(
            model_name='advertisementphotos',
            name='photo_url',
            field=models.CharField(max_length=200, verbose_name='ссылка на изображение'),
        ),
        migrations.AlterField(
            model_name='advertisementphotos',
            name='w_hash',
            field=models.CharField(max_length=20, verbose_name='w-хэш картинки'),
        ),
    ]
