# Generated by Django 3.2.3 on 2021-07-07 14:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('search_cars', '0005_auto_20210707_1729'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisementphotos',
            name='adv_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='search_cars.advertisement', verbose_name='Объявление'),
            preserve_default=False,
        ),
    ]
