# Generated by Django 3.2.3 on 2021-07-08 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search_cars', '0006_advertisementphotos_adv_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisement',
            name='site',
            field=models.CharField(default='auto.ru', max_length=30, verbose_name='Сайт объявления'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='advertisement_id',
            field=models.IntegerField(unique=True, verbose_name='Id объявления'),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='advertisement_url',
            field=models.CharField(max_length=300, verbose_name='Ссылка на объявление'),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='info',
            field=models.TextField(verbose_name='Текст объявление'),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='model',
            field=models.CharField(max_length=200, verbose_name='Модель'),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='year',
            field=models.CharField(max_length=4, verbose_name='Год авто'),
        ),
    ]
