# Generated by Django 3.2.3 on 2021-07-08 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search_cars', '0007_auto_20210708_1058'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisement',
            name='original',
            field=models.BooleanField(default=True, verbose_name='Оригинальное объявление'),
            preserve_default=False,
        ),
    ]
