# Generated by Django 3.2.3 on 2021-07-10 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search_cars', '0008_advertisement_original'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisement',
            name='similar_advertisement',
            field=models.ManyToManyField(related_name='_search_cars_advertisement_similar_advertisement_+', to='search_cars.Advertisement'),
        ),
    ]
