# Generated by Django 3.2.3 on 2021-07-10 07:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('search_cars', '0009_advertisement_similar_advertisement'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='advertisementphotos',
            name='avg_hash',
        ),
        migrations.RemoveField(
            model_name='advertisementphotos',
            name='d_hash',
        ),
        migrations.RemoveField(
            model_name='advertisementphotos',
            name='p_hash',
        ),
        migrations.RemoveField(
            model_name='advertisementphotos',
            name='w_hash',
        ),
    ]
