# Generated by Django 3.2.3 on 2021-07-11 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search_cars', '0010_auto_20210710_1043'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisement',
            name='color',
            field=models.CharField(default='синий', max_length=15, verbose_name='Цвет автомобиля'),
            preserve_default=False,
        ),
    ]
