# Generated by Django 3.2.3 on 2021-07-15 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search_cars', '0011_advertisement_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisement',
            name='added_at',
            field=models.DateTimeField(blank=True, verbose_name='Дата добавления в базу'),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='color',
            field=models.CharField(blank=True, max_length=15, verbose_name='Цвет автомобиля'),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='created_at',
            field=models.DateTimeField(db_index=True, verbose_name='Дата появления объявления'),
        ),
    ]
