# Generated by Django 3.2.5 on 2021-07-18 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search_cars', '0012_auto_20210715_1422'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisement',
            name='added_at',
            field=models.DateTimeField(blank=True, verbose_name='Дата появления объявления'),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='created_at',
            field=models.DateTimeField(db_index=True, verbose_name='Дата добавления в базу'),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='similar_advertisement',
            field=models.ManyToManyField(blank=True, related_name='_search_cars_advertisement_similar_advertisement_+', to='search_cars.Advertisement'),
        ),
    ]
