# Generated by Django 3.2.5 on 2021-07-18 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search_cars', '0014_auto_20210718_1903'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisementphotos',
            name='avg_hash',
            field=models.CharField(default=1, max_length=16, verbose_name='Изображение'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='advertisementphotos',
            name='photo',
            field=models.ImageField(default=1, upload_to='', verbose_name='Изображение'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='advertisementphotos',
            name='photo_url',
            field=models.CharField(max_length=200, verbose_name='Ссылка на изображение'),
        ),
    ]
