# Generated by Django 3.2.5 on 2021-07-19 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search_cars', '0015_auto_20210718_2051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisement',
            name='original',
            field=models.BooleanField(blank=True, verbose_name='Оригинальное объявление'),
        ),
    ]
