# Generated by Django 3.2.5 on 2021-07-19 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search_cars', '0016_alter_advertisement_original'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisement',
            name='advertisement_id',
            field=models.IntegerField(db_index=True, unique=True, verbose_name='Id объявления'),
        ),
    ]
