# Generated by Django 3.2.5 on 2021-07-19 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search_cars', '0017_alter_advertisement_advertisement_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisement',
            name='original',
            field=models.BooleanField(null=True, verbose_name='Оригинальное объявление'),
        ),
    ]
