# Generated by Django 3.2.5 on 2021-07-19 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search_cars', '0018_alter_advertisement_original'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisementphotos',
            name='avg_hash',
            field=models.CharField(max_length=16, null=True, verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='advertisementphotos',
            name='photo',
            field=models.ImageField(null=True, upload_to='', verbose_name='Изображение'),
        ),
    ]
